### ISSUE TITLE
Support for Swift 05-09

### ISSUE THREAD

**Issue by coryalder** [qutheory/fluent-sqlite#6]
I've got a working fix over at https://github.com/coryalder/fluent-sqlite/commit/c8f73ed1f91ecf426672f880b59405dbbc66e6bf

However I'm hesitant to submit a pull request because I'm not sure of the full consequences of my change. While the current release of Fluent is pinned to 05-03, it compiles fine under 05-09. FluentSQLite does not.

The reason I'd like to use 05-09 is Vapor is currently targeting that version of Swift.

**Comment by tanner0101** [comment]
Yeah this needs to be updated to work with 05-09. I've added this to the 0.4 milestone.

**Comment by tanner0101** [comment]
fixed in #7
